### ISSUE TITLE
[Bug] Упущен запуск скрипта. Docker

### ISSUE THREAD

**Issue by ijo42** [MrZillaGold/VK2Discord#102]
**Описание ошибки**
Смотря на 311db00 можно заметить что инструкция `CMD [ "npm", "start" ]` была удалена.
На замену ей ничего не пришло. В связи с этим при попытке запуска имейджа получаем пустой лог. 

**Шаги воспроизведения**
1. Спуллить последний имейдж
2. Запустить, смонтировав конфиг
3. Получаем пустой лог

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| VK2Discord | `2.1.0`    |

Удалось запустить, вызвав `npm start`, но, возможно, с TypeScript запускать надо иначе, не рискну делать PR

**Comment by ijo42** [comment]
Рано. Сейчас доработаю репорт...

**Comment by MrZillaGold** [comment]
Вроде исправил, снимок залил, проверьте пожалуйста. https://github.com/MrZillaGold/VK2Discord/commit/b41b50290658c89fec511853cce5e9ef9c899758

**Comment by ijo42** [comment]
Было бы логичнее использовать ENTRYPOINT, но тоже жизнеспособно.
Есть возможность связаться в дискорде? Есть пару идей, но лучше предварительно обсудить

**Comment by MrZillaGold** [comment]
@ijo42 https://discord.gg/DUBkqFUshQ
