### ISSUE TITLE
[Bug] Переполнение текстового поля с вложениями

### ISSUE THREAD

**Issue by LWJerri** [MrZillaGold/VK2Discord#113]
**Описание ошибки**
Иногда проскакивает вот такая ошибка:
![image](https://user-images.githubusercontent.com/50290430/107655200-016bdf00-6c8c-11eb-8586-c07870394346.png)

**Шаги воспроизведения**
1. Парсит посты.
2. Выбивает ошибку.

**Скриншоты**
Выше.

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| NodeJS     | `latest`    |
| npm        | `latest`    |
| VK2Discord | `latest`    |

**Comment by LWJerri** [comment]
Можно ли это как-то игнорировать и отправлять максимально допустимое кол-во фото?

**Comment by MrZillaGold** [comment]
Проблема в том, что строка с вложениями имеет ограничение по символам, скрипт это не учитывает.
Можно пожалуйста пример записи с проблемой?

**Comment by LWJerri** [comment]
> Проблема в том, что строка с вложениями имеет ограничение по символам, скрипт это не учитывает.
> Можно пожалуйста пример записи с проблемой?

Я не могу отследить эту запись, т.к одновременно парсится около 100 пабликов.

**Comment by MrZillaGold** [comment]
https://github.com/MrZillaGold/VK2Discord/releases/tag/2.1.3
