### ISSUE TITLE
[Bug] npm не удается найти скрипт запуска

### ISSUE THREAD

**Issue by Kryatov** [MrZillaGold/VK2Discord#124]
**Описание ошибки**
Ошибка старта скрипта

**Шаги воспроизведения**
В командной строке по инструкции были выполнены все шаги настройки скрипта вплоть до указания токена группы и адреса вебхука, однако при попытке старта скрипта наблюдается следующая ошибка
_npm ERR! missing script: start_

**Скриншоты**
![image](https://user-images.githubusercontent.com/79804925/109429196-56de1500-7a1c-11eb-9545-4e7093516572.png)

**Логи**
[2021-02-28T18_07_30_267Z-debug.log](https://github.com/MrZillaGold/VK2Discord/files/6057520/2021-02-28T18_07_30_267Z-debug.log)

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| NodeJS     | `15.8.0`    |
| npm        | `7.6.0`    |
| VK2Discord | `2.1.4`    |

**Comment by MrZillaGold** [comment]
'package.json' распаковали из архива? Можно скриншот из папки со скриптом и файла 'package.json', пожалуйста.

**Comment by MrZillaGold** [comment]
Закрываю issue из-за неактивности. Если у вас остались вопросы, не стесняйтесь пинговать.
