### ISSUE TITLE
[Bug] При запуске

### ISSUE THREAD

**Issue by levarar** [MrZillaGold/VK2Discord#126]
[2021-03-03T11_49_08_677Z-debug.log](https://github.com/MrZillaGold/VK2Discord/files/6075745/2021-03-03T11_49_08_677Z-debug.log)
**Описание ошибки**
При запуске скрипта выдаёт ошибку, делалось всё по инструкции, использовался токен сообщества, выдаёт ошибку со скрина ниже, при попытке запустить командой с package.json (node --experimental-modules --experimental-json-modules --unhandled-rejections=warn --es-module-specifier-resolution=node ./dist/index.js) летит другая ошибка с 3 скриншота

**Скриншоты**
По возможности прикрепите скриншот с ошибкой, это поможет в поиске причины проблемы.
![image](https://user-images.githubusercontent.com/68510813/109801537-a7798c00-7c2f-11eb-9b17-f002dd0a0735.png)
![image](https://user-images.githubusercontent.com/68510813/109801615-c415c400-7c2f-11eb-8c35-f6a2d8fbcd61.png)
![image](https://user-images.githubusercontent.com/68510813/109801931-35ee0d80-7c30-11eb-9875-f0de8e07436d.png)

**Версии**
| Debian  | 10| 
| ---------- | ------ |
| NodeJS     | 14.15.1`    |
| npm        | `6.14.8`    |
| VK2Discord | `Последняя скаченная с Вашего гитхаба`    |

**Comment by levarar** [comment]
Решил проблему

**Comment by MrZillaGold** [comment]
Сборку скрипта необходимо загружать из выпусков, а не из корня репозитория, либо собирать самостоятельно при помощи `npm run build`
