### ISSUE TITLE
Добавление нескольких групп в "group_id"

### ISSUE THREAD

**Issue by hmf0ff** [MrZillaGold/VK2Discord#131]
**Привет, только начинаю развиваться в сфере скриптов, прочитал ваш Issues с чуваком, про добавление 2 + групп.
Но как я понял, вы добавили возможность добавления нескольких Веб-Хуков, а не групп.
Очень буду благодарен, если вы поможете разобраться или дадите ответ, потому что, хотелось бы уместить это всё в один процесс, а не в 5.
Спасибо!**
@MrZillaGold

**Comment by MrZillaGold** [comment]
Обратите внимание на [пример конфига](https://github.com/MrZillaGold/VK2Discord/blob/master/config_example.json) в нем как раз показана структура с несколькими кластерами.

**Comment by hmf0ff** [comment]
**@MrZillaGold 
Токен в одном кластере должен отличаться от другого?**

**Comment by MrZillaGold** [comment]
Если вы используете токен пользователя - то его можно переиспользовать в нескольких кластерах, только нужно просчитать правильный интервал. На 1 токен пользователя доступно 5000 вызовов метода для получения записей.

При использовании токена группу в этом нет смысла, так как посты просто будут дублироваться.

**Comment by hmf0ff** [comment]
Спасибо, очень помогли. Интервалы уже высчитал.
Удачи вам, буду дальше следить за тем, что вы делаете)
