### ISSUE TITLE
Не могу запустить бота

### ISSUE THREAD

**Issue by warlockshade** [MrZillaGold/VK2Discord#145]
При написании npm start выдаёт ошибки, бот не запускается. Опыта ноль, делал всё по описанию.

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| NodeJS     | `14.16.0`    |
| npm        | `6.14.11`    |
| VK2Discord | `последняя версия, которая есть на гитхабе`    |

![vk2discord](https://user-images.githubusercontent.com/42187567/114280199-e4ac1780-9a40-11eb-9c49-0e3c7ae49093.png)
[2021-04-10T14_57_34_549Z-debug.log](https://github.com/MrZillaGold/VK2Discord/files/6290486/2021-04-10T14_57_34_549Z-debug.log)

**Comment by MrZillaGold** [comment]
Скрипт необходимо загружать из релизов, а не из корня репозитория.

https://github.com/MrZillaGold/VK2Discord/releases/tag/2.1.4

**Comment by FalconSokol1** [comment]
На хостинг или как это называется?

**Comment by MrZillaGold** [comment]
Любой VDS хостинг подойдет
