### ISSUE TITLE
Публикация определенных новостей из ВК в Discord

### ISSUE THREAD

**Issue by papay88** [MrZillaGold/VK2Discord#159]
Здравствуйте.
Хотел бы внести на ваше рассмотрение возможность переноса определенных записей из ВК в Discord.
Понимаю, что возможно это не реализуемо, но может есть какая-нибудь возможность перехватывать их по определенным тегам добавленным к записи.

**Пример:**
У записи присутствует тег #discord _(любой тег вообще)_, ваш скрипт видит и отправляет в discord только запись с таким тегом.

**Comment by MrZillaGold** [comment]
Прочитайте [описание полей конфигурации](https://github.com/MrZillaGold/VK2Discord/blob/master/CONFIG_FIELDS.md), такая возможность уже есть

**Comment by papay88** [comment]
Спасибо вам за наводку, плохо ознакомился с документацией.
