### ISSUE TITLE
Прикреплять все изображения поста к сообщению

### ISSUE THREAD

**Issue by MrZillaGold** [MrZillaGold/VK2Discord#20]

**Comment by MrZillaGold** [comment]
Тут будет необходимо использовать классы

**Comment by MrZillaGold** [comment]
Разбивка на разные embedы реализована, но появилась проблема с синхронной отправкой сообщений, некоторые сообщение отправляются быстрее чем остальные, порядок нарушается. Пока не придумал, что с этим можно сделать.
https://github.com/MrZillaGold/VK2Discord/blob/363722a80ecf4d44cef7c5c8a1fe3810f95a1f30/modules/sender.mjs#L117

**Comment by Dancbeunny98** [comment]
![image](https://user-images.githubusercontent.com/37336183/78362736-467ea980-75c3-11ea-993b-907e38ea7424.png)

Все отображается и отправляется хорошо. Не нужно ничего тут менять!

**Comment by MrZillaGold** [comment]
Отказываюсь от реализации, сообщения должны быть лаконичными и содержать в себе САМУЮ важную информацию. По возможности пользователь может перейти по ссылке на пост и уже подробнее ознакомится с ним ВКонтакте.

Возможно Discord позволит в будущем прикреплять к вебхуку несколько изображений, как это сделано с превью Twitter ссылок.

**Comment by MrZillaGold** [comment]
https://github.com/discord/discord-api-docs/issues/2007

**Comment by MrZillaGold** [comment]
https://github.com/MrZillaGold/VK2Discord/issues/65

Это изменение позволит не дожидаться реализации функционала в **webhook-discord**

**Comment by MrZillaGold** [comment]
https://github.com/MrZillaGold/VK2Discord/commit/31168ae134d706baf5eb831f71e4143d0e362f59
