### ISSUE TITLE
[Bug] Ключевые слова

### ISSUE THREAD

**Issue by Silence02ru** [MrZillaGold/VK2Discord#201]
**Описание ошибки**
Оставляю массив пустым  **keywords** и бот перестает постить записи с ВК
Пробовал по Longpoll API и по токену

**Шаги воспроизведения**
1. Удалить в конфинге все ключевые слова
2. Запустить бота
4. Получаю ошибку: **Новая запись в кластере #6 не соответствует ключевым словам, игнорируем ее.**

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| NodeJS     | `v15.14.0`    |
| npm        | `7.7.6`    |
| VK2Discord | `2.1.5`    |

**Comment by Silence02ru** [comment]
![image](https://user-images.githubusercontent.com/61424512/122459210-1655d780-cfca-11eb-8b0b-d23d35bc7881.png)
Появилась еще 2 ошибки

**Comment by MrZillaGold** [comment]
Ошибку с `is_donut` поправил. 

Не могли бы предоставить ссылку на запись с которой происходит проблема проверки ключевых слов? Не получается воспроизвести.

**Comment by Silence02ru** [comment]
Как ни странно, теперь все прекрасно работает. Ничего не перекачивал, запустил вчерашний скрипт.

**Comment by MrZillaGold** [comment]
Исправление бага с `is_donut` доступно в [последнем релизе](https://github.com/MrZillaGold/VK2Discord/releases/tag/2.1.6).
