### ISSUE TITLE
Преобразование #хештегов в ссылки

### ISSUE THREAD

**Issue by Dancbeunny98** [MrZillaGold/VK2Discord#23]
При нажатии на  #хештег  человеку будет выдаваться что-то типа - `https://vk.com/publicid/#хештег`

**Comment by MrZillaGold** [comment]
https://github.com/MrZillaGold/VK2Discord/commit/de2fd3210309489c89bc9410f73e66871370871c
![image](https://user-images.githubusercontent.com/42776347/78456818-57c1d600-76e9-11ea-8bc9-7fa6f5787d0f.png)

**Comment by MrZillaGold** [comment]
https://github.com/MrZillaGold/VK2Discord/issues/30

**Comment by Dancbeunny98** [comment]
Ошибку можно изменить путем изменения ссылки на wall-publicid-///

**Comment by Dancbeunny98** [comment]
![image](https://user-images.githubusercontent.com/37336183/78708478-e1a4b580-791a-11ea-97b7-1dc24ce4771b.png)
![image](https://user-images.githubusercontent.com/37336183/78708490-e7020000-791a-11ea-9e1a-dee32b19d008.png)

Тут вот такая ошибка

**Comment by MrZillaGold** [comment]
Вышеперечисленные проблемы решены https://github.com/MrZillaGold/VK2Discord/commit/19a7aa4bfde990d638f6a1e5c492f8c4f40ee058. Если будут ошибки связанные с хештегами отпишите.

**Comment by Dancbeunny98** [comment]
> Вышеперечисленные проблемы решены [19a7aa4](https://github.com/MrZillaGold/VK2Discord/commit/19a7aa4bfde990d638f6a1e5c492f8c4f40ee058). Если будут ошибки связанные с хештегами отпишите.

В данный момент открывает, но общую ленту новостей по "#хештегу", а не по сообществу.

**Comment by MrZillaGold** [comment]
Если хештег не навигационный, то поиск по нему и должен открываться по всей ленте, такая логика и ВКонтакте
