### ISSUE TITLE
Возможность упоминания ролей в сообщении 

### ISSUE THREAD

**Issue by Dancbeunny98** [MrZillaGold/VK2Discord#24]
Упоминание ролей в дискорд при появлении новости. выглядит примерно так.

![image](https://user-images.githubusercontent.com/37336183/78363460-75e1e600-75c4-11ea-849e-2d4a6c809280.png)

**Comment by MrZillaGold** [comment]
Discord не позволяет использовать упоминания в WebHooks

**Comment by MrZillaGold** [comment]
Данная возможность добавлена в последнем [релизе](https://github.com/MrZillaGold/VK2Discord/releases/tag/1.9.4)
