### ISSUE TITLE
Возможность использования скрипта для нескольких групп

### ISSUE THREAD

**Issue by Homosanians** [MrZillaGold/VK2Discord#26]
Указание, использование, создание разных файлов конфигурации

Относится к Issue #25

Цель: повышение юзабилити.

Проблема: для того, чтобы создать несколько ботов для публикации из разных пабликов, необходимо копировать файлы программы в разные папки и запускать их по отдельности, настраивая конфиги.

Способы решения:
1. использование парсинга конфигураций через аргументы;
2. использование кастомных файлов конфигурации с указанием расположения файла в аргументе типа --config {path}.

Дополнение ко способам 1 и 2: в этих случаях файл конфигураций по умолчанию должен игнорироваться.

Дополнение ко способу 2: необходимо реализовать создание шаблона файла конфигураций (например, --generate-config {path}).

Проблема в ходе реализации способа 1 и 2 
Файл с опубликованными постами news.json, используемый по умолчанию, может вызвать проблемы. Например, при записи в файл одним ботом, другому будет отказано системой. Также, со временем, файл будет быстрее переполняться и станет непонятным для администратора. Необходимо будет создать отдельный файл опубликованных новостей для каждого файла конфигураций, либо создать комбинированный файл с конфигурацией и списком опубликованных новостей.

Все последующие принятые решения рекомедуется оставлять в этой теме.

**Comment by MrZillaGold** [comment]
Я думал над этим.

Изначально я думал над массивом со списком всех групп, но тут встретилась другая проблема.
У ВКонтакте есть лимит на использование метода wall.get, 5000 вызовов в сутки.
Для 1 паблика такой лимит не будет даже заметен, посты можно проверять раз в 17 секунд, но никак для большего количества групп.

В данный момент более хорошим и оптимальным, по моему мнению, решением будет возможность указания несколько токенов страниц, которые будут рандомно использоваться в ходе работе скрипта. При этом пользователь будет предупреждаться об оптимальном количестве токенов для работы с n-количеством групп, количество должно будет высчитываться на основе интервала и количества групп.

При работе с LongPoll такая структура никак не помешает. При использовании нескольких групп будет браться токен с таким же индексом как и id группы.

Скорее всего структура конфига будет переделана.
Структура опубликованых постов будет также переделана.

Если у меня ещё будут какие-то мысли, отпишу.

**Comment by MrZillaGold** [comment]
Еще более лучшее решение:

Необходимо использовать массив в который можно будет добавлять объекты.
Объекты в свою очередь будут иметь такую структуру:

```
{
    "token": "токен", // Токен от страницы или группы ВКонтакте
    "group_id": "public1", // ID группы или пользователя ВКонтакте от которого брать новости.
    "keywords": [], // Ключевые слова, через запятую, для публикации записи.
    "filter": true,
    "longpoll": false, // Использовать Longpoll API. true = Вкл. / false = Выкл.
     "interval": 30, // Интервал, если пользователь не использует LongPoll
     "webhook_urls": [
         "https://discordapp.com/api/webhooks/",
         "https://discordapp.com/api/webhooks/",
         ...
    ], // Ссылки на Webhook, можно использовать несколько ссылок на разные каналы Discord.
  }
```

Такой структурой мы сможем решить данную проблему, а также позволить пользователям одновременно использовать токены обычных страниц и LongPoll API, и дадим более гибкую настройку.

**Comment by Homosanians** [comment]
Согласен с последним решением: не будет много разных файлов и запущенных процессов. Что на счёт news.json? Он будет один для всех исполнителей каждого объекта конфига?

**Comment by MrZillaGold** [comment]
Он будет также состоять из массива в котором будут находиться объекты, в каждом объекте будет ID-Группы, что позволит проверять и добавлять пост по ID

**Comment by MrZillaGold** [comment]
В принципе, реализовано. Если будут проблемы связанные с этой issue, пинганите.
