### ISSUE TITLE
heroku crash

### ISSUE THREAD

**Issue by Dancbeunny98** [MrZillaGold/VK2Discord#28]
![image](https://user-images.githubusercontent.com/37336183/78461027-9c8c4380-76ce-11ea-8886-39a5069971b1.png)

Для стабильной работы на heroku нужно просто в `Procfile` написать - worker: npm start $PORT

**Comment by Dancbeunny98** [comment]
![image](https://user-images.githubusercontent.com/37336183/78461109-f68d0900-76ce-11ea-933b-42d0e42a3d9e.png)
Вот такой старт должен быть.

**Comment by Dancbeunny98** [comment]
а вот это в конфигурации
![image](https://user-images.githubusercontent.com/37336183/78461122-115f7d80-76cf-11ea-9100-53898f2b7c72.png)

**Comment by MrZillaGold** [comment]
Это не веб приложение, от указания порта ничего не измениться и не улучшиться

**Comment by MrZillaGold** [comment]
Изначально ты приложение для node.js запускаешь в web, поэтому и крашит, на втором скриншоте оно уже запускается от worker`a, как и должно запускаться изначально

**Comment by Dancbeunny98** [comment]
Ясно. Значит я такой "глупый".
