### ISSUE TITLE
#хештеги работают с ошибкой

### ISSUE THREAD

**Issue by Dancbeunny98** [MrZillaGold/VK2Discord#30]
При переходе на хештег из дискорд вылазит ошибка 

![image](https://user-images.githubusercontent.com/37336183/78507652-087fb200-778a-11ea-933d-37a9f8cb0233.png)
![image](https://user-images.githubusercontent.com/37336183/78507675-3b29aa80-778a-11ea-9536-cc528ccd4ef5.png)

**Comment by Dancbeunny98** [comment]
На русских символах так.

**Comment by MrZillaGold** [comment]
Не нужно плодить большое количество issue на одну и ту же тему, можно просто попросить переоткрыть первую.
