### ISSUE TITLE
Ошибка получения токена ВК

### ISSUE THREAD

**Issue by Saikel** [MrZillaGold/VK2Discord#310]
Добрый день,

При переходе по ссылке в readme в разделе "У меня нет прав администратора в группе и я хочу использовать токен страницы". https://vk.cc/9bJ69C выдает ошибку:
**{"error":"invalid_request","error_description":"application is disabled"}**

Как теперь можно авторизоваться в ВК для получения новостей через бота?
Бот тоже перестал авторизовываться в ВК и выдает ошибку:
**[!] Произошла ошибка при получении ID-ресурса.
APIError: Code №5 - User authorization failed: invalid session.**

**Comment by MrZillaGold** [comment]
ВКонтакте отключили приложение которое указано в инструкции, ссылку обновлю.
Токен можно получить через это приложение: https://oauth.vk.com/authorize?client_id=6121396&scope=1073737727&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token&revoke=1
