### ISSUE TITLE
Возможность постить в канал в зависимости от тега

### ISSUE THREAD

**Issue by BlockStun** [MrZillaGold/VK2Discord#34]
Прошу помощи, так как не нашёл похожего вопроса ни среди открытых, ни среди закрытых.

Можно ли каким-то образом изменить config.json так, чтобы посты приходили в конкретный канал в зависимости от используемого тега? С учётом того, что все посты из одного и того же сообщества.

Например, есть два канала. Соответственно, два вебхука. На каждый есть свой тег, который будет во Вконтакте. То есть при появлении поста отсматриваются теги, и в зависимости от присутствующего тега идет пост в соответствующий канал.

**Comment by MrZillaGold** [comment]
Реализую в следующей версии

**Comment by MrZillaGold** [comment]
Новый функционал реализовать не придется, вы можете использовать несколько кластеров с одним и тем же id группы только настроив их на разные ключевые слова и каналы соответственно.
Например:
```
"clusters": [
		{
			"vk": {
				"group_id": "club1",
                                 "keywords": ["слово1"]
			},
			"discord": {
				"webhook_urls": [ 
					"вебхук1"
				],
			}
		},
                {
			"vk": {
				"group_id": "club2",
                                 "keywords": ["слово2"]
			},
			"discord": {
				"webhook_urls": [ 
					"вебхук2"
				],
			}
		},
	]
```

**Comment by BlockStun** [comment]
Удалось настроить. Вариант рабочий. Спасибо!
