### ISSUE TITLE
[Bug] WEBHOOK_URL_INVALID

### ISSUE THREAD

**Issue by vurhe** [MrZillaGold/VK2Discord#343]
При запуске последней версии (3.0.0) вылетает ошибка:

Error [WEBHOOK_URL_INVALID]: The provided webhook URL is not valid.
    at new WebhookClient (C:\vk2dis\node_modules\discord.js\src\client\WebhookClient.js:36:42)
    at file:///C:/vk2dis/dist/modules/Sender.js:53:77
    at Array.map (<anonymous>)
    at Sender.send (file:///C:/vk2dis/dist/modules/Sender.js:53:63)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/vk2dis/node_modules/middleware-io/lib/index.mjs:276:9 {
  [Symbol(code)]: 'WEBHOOK_URL_INVALID'
}

Проверял на Node17 и Node16 на Ubuntu18 и Windows10. При использовании 2.1.8 такой проблемы не наблюдается. Все параментры config.json идентичны кроме обновлённых; скрипты запускались с разницей в пару минут. Так что проблема не в конфиге (ничего в нём не трогал, кроме token, group_id,webhook_urls) или вебхуке.

**Comment by MrZillaGold** [comment]
С какого домена начинается вебхук? Проверьте чтобы он был discord.com.

**Comment by vurhe** [comment]
Домен выглядит как
https://discordapp.com/api/webhooks/.../...
Также как и у вас в config_example.json (https://discordapp.com/api/webhooks/730807540459241472/...)
Правильно ли я понял, что должен поменять домен на discord.com
[config_example.log](https://github.com/MrZillaGold/VK2Discord/files/7474051/config_example.log)
?

**Comment by MrZillaGold** [comment]
Да, Discord переехали на новый домен и изменили это в библиотеке, в примере поправлю.
