### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Dancbeunny98** [MrZillaGold/VK2Discord#345]
![image](https://user-images.githubusercontent.com/37336183/140627182-a4e51999-d9f0-4983-a4f9-d66018c705b9.png)

**Comment by MrZillaGold** [comment]
В конфиге не хватает некоторых полей.
Вызовите команду `npm run-script update` для автоматического обновления.

**Comment by Dancbeunny98** [comment]
![image](https://user-images.githubusercontent.com/37336183/140651433-2531c4f0-5473-4704-ac25-5ec7a0eae367.png)

**Comment by Dancbeunny98** [comment]
Исправил. Поправь конфиги. там есть ошибка в номере версии
