### ISSUE TITLE
пишет что лишняя запятая (скрины ниже ), код с релиза переустановил, запятая так и осталась (проблема только на последнем релизе на 3.0.0 всё работает)

### ISSUE THREAD

**Issue by sirok1** [MrZillaGold/VK2Discord#361]
![image](https://user-images.githubusercontent.com/75698544/142920576-0dcf5111-3fc0-4103-8175-b3d5b8add4b0.png)
![image](https://user-images.githubusercontent.com/75698544/142920580-3ba8ebe7-9fdf-42cc-bdad-5c5a85f9eab0.png)

**Comment by sirok1** [comment]
прописал ещё раз npm i, всё равно ругается на запятую 
![image](https://user-images.githubusercontent.com/75698544/142920866-6c53185a-7709-4f95-babe-14d587fe0168.png)

**Comment by MrZillaGold** [comment]
Node.js обновите до 17 версии
