### ISSUE TITLE
Не может считать параметр MinLength, стоит 1

### ISSUE THREAD

**Issue by MrZillaGold** [MrZillaGold/VK2Discord#386]
Не может считать параметр MinLength, стоит 1
![gfgfgfg](https://user-images.githubusercontent.com/96467798/146895380-cafbd204-db54-464b-83d9-7dcc6ca3ec4f.PNG)
.

_Originally posted by @CJIuBka in https://github.com/MrZillaGold/VK2Discord/discussions/384_

**Comment by MrZillaGold** [comment]
@CJIuBka можно ссылку на пост на котором происходит обработка?

**Comment by MrZillaGold** [comment]
Обновил версию библиотеки, скорее всего пофикшено.

**Comment by CJIuBka** [comment]
> Обновил версию библиотеки, скорее всего пофикшено.

К сожалению проблема осталась. Скачал новую версию, все поменял и ничего. Сама ошибка возникает не при репосте, а при прописке в консоли "npm start", то есть не может обнаружить сервер Discord, как я понял.

**Comment by MrZillaGold** [comment]
Закрываю проблему из-за недостаточного количества информации.
