### ISSUE TITLE
Токен группы не работает

### ISSUE THREAD

**Issue by redcarti** [MrZillaGold/VK2Discord#39]
Привет. Пытался пропустить токен группы, не пошел. В документации метода [wall.get](https://vk.com/dev/wall.get) не написано про токен группы. Думаю, что лучше убрать из примера, что можно использовать его.

**Comment by MrZillaGold** [comment]
Думаю вам нужно внимательно прочитать инструкцию к скрипту

**Comment by redcarti** [comment]
При токене группы пишется ошибка, без токена группы, а то есть с токеном пользователя всё отлично.
![image](https://user-images.githubusercontent.com/55404819/85015644-ba236200-b181-11ea-9d1b-bbdd2a80a488.png)

**Comment by redcarti** [comment]
И именно ошибка авторизации через токен группы.

**Comment by MrZillaGold** [comment]
Если ты сделаешь все шаги по инструкции никакой ошибки не будет, у токена есть права на управление группой?

**Comment by redcarti** [comment]
М, понял. ``longpoll`` не стоит.

**Comment by MrZillaGold** [comment]
Если бы вы внимательно прочитали инструкцию, то вы бы не тратили не свое время, ни мое. Если вопросов больше нет, можете закрыть Issue
