### ISSUE TITLE
Инструкция по установке на linux (debian)

### ISSUE THREAD

**Issue by xeeek** [MrZillaGold/VK2Discord#392]
В инструкции по установке написано всё для windows, возможно ли дописать ее для linux, ибо установка производится совершенно по другому, да и большинство как мне кажется серверов работают именно на этой системе.

**Comment by Silence02ru** [comment]
## Для начала работы с VK2Discord на базе Linux следуйте инструкции ниже

1. Перед установкой Node.js , убедитесь, что у вас установлен пакет curl.

`sudo apt install curl -y`

2. Установка Node.js 17 на Ubuntu / Debian / Linux Mint

`curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -`

`sudo apt-get install nodejs`

3. Чтобы проверить установку и подтвердить сборку версии Node.js и NPM, используйте следующую команду

`node -v`

`npm -v`

**Comment by MrZillaGold** [comment]
Дошли руки - вынес в основную инструкцию. Спасибо!
