### ISSUE TITLE
Возможность отключения публикации постов VK Donut

### ISSUE THREAD

**Issue by Venterok** [MrZillaGold/VK2Discord#44]
![изображение](https://user-images.githubusercontent.com/67825103/86523844-3785ec80-be7b-11ea-8b44-a7b954eb1cc7.png)
Vk Donut новая функция вк, через которую можно делать посты только для донатов, но vk2discord публикует и те и другие.

**Comment by MrZillaGold** [comment]
Ждем появления нужных полей в API VK

**Comment by MrZillaGold** [comment]
[Поля в API появились](https://vk.com/wall-1_396877). Реализую в следующем обновлении.

**Comment by MrZillaGold** [comment]
https://github.com/MrZillaGold/VK2Discord/commit/373536458e3f6ad951affea8afb39c30ca4978b0

**Comment by MrZillaGold** [comment]
Доступно в версии 2.0.0
