### ISSUE TITLE
Запуск на Ubuntu

### ISSUE THREAD

**Issue by NITDroid1995** [MrZillaGold/VK2Discord#46]
Проблема такая, что на машине с Ubuntu проблема с запуском при использовании флагов
`> vk2discord@1.7.0 init /home/VKNews
> nodejs --experimental-modules --experimental-json-modules --es-module-specifier-resolution=nodejs index.mjs

nodejs: bad option: --experimental-json-modules
nodejs: bad option: --es-module-specifier-resolution=nodejs
`

Я пробовал и nodejs и просто node. Результат один. 
Без флагов не стартует вообще. Жалуется на cluster = {}; На знак равно.

А хотелось запустить в скрин чтобы оно там крутилось себе на серваке и все.

ЛОГ:
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle vk2discord@1.7.0~prestart: vk2discord@1.7.0
6 info lifecycle vk2discord@1.7.0~start: vk2discord@1.7.0
7 verbose lifecycle vk2discord@1.7.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle vk2discord@1.7.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/VKNews/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle vk2discord@1.7.0~start: CWD: /home/VKNews
10 silly lifecycle vk2discord@1.7.0~start: Args: [ '-c', 'npm run check && npm run init' ]
11 silly lifecycle vk2discord@1.7.0~start: Returned: code: 9  signal: null
12 info lifecycle vk2discord@1.7.0~start: Failed to exec start script
13 verbose stack Error: vk2discord@1.7.0 start: `npm run check && npm run init`
13 verbose stack Exit status 9
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid vk2discord@1.7.0
15 verbose cwd /home/VKNews
16 verbose Linux 5.4.0-40-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 9
22 error vk2discord@1.7.0 start: `npm run check && npm run init`
22 error Exit status 9
23 error Failed at the vk2discord@1.7.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 9, true ]
`

**Comment by MrZillaGold** [comment]
https://github.com/MrZillaGold/VK2Discord/issues/22
