### ISSUE TITLE
Ошибка ВКонтакте 10 при запуске скрипта

### ISSUE THREAD

**Issue by tatorhe** [MrZillaGold/VK2Discord#483]
npm -v: 8.5.5
node -v: v17.9.0
lsb_release -a: Ubuntu 18.04.6 LTS
version: https://github.com/MrZillaGold/VK2Discord/releases/tag/3.0.1
Пробовал переустановить - та же ошибка

npm start:

> > vk2discord@3.0.1 prestart
> > node --experimental-modules --experimental-json-modules --unhandled-rejections=warn --es-module-specifier-resolution=node ./scripts/check.js
> 
> (node:24606) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:24606) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
> 
> > vk2discord@3.0.1 start
> > node --experimental-modules --experimental-json-modules --unhandled-rejections=warn --es-module-specifier-resolution=node ./dist/index.js
> 
> (node:24618) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:24618) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
> [VK2Discord] Запущен.
> [VK2Discord] Кластер #1 подключен к ВКонтакте с использованием LongPoll!
> ExecuteError: Code №10 - Internal server error
>     at file:///root/VK2Discord/node_modules/vk-io/lib/index.mjs:1651:73
>     at Array.map (<anonymous>)
>     at ParallelWorker.execute (file:///root/VK2Discord/node_modules/vk-io/lib/index.mjs:1651:57)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
>   code: 10,
>   params: [],
>   method: 'storage.get',
>   [cause]: undefined
> }
>

**Comment by MrZillaGold** [comment]
От какого приложения генерируете токен?

**Comment by vurhe** [comment]
Не понял вопроса. Уточните. Токен и вебхук генерирую, как в инструкции

**Comment by MrZillaGold** [comment]
А если попробовать [отсюда](https://oauth.vk.com/authorize?client_id=2685278&scope=1073737727&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token&revoke=1) токен сгенерировать, ошибка остается?

**Comment by vurhe** [comment]
да, остаётся

**Comment by MrZillaGold** [comment]
Можно скриншот конфига? Конфиденциальные поля нужно замазать.

**Comment by vurhe** [comment]
[config.json.txt](https://github.com/MrZillaGold/VK2Discord/files/8502553/config.json.txt)

Я даже могу файл отправить. По сути, я ничего не менял. Только прописал token, group_id, webhook_urls и всё. Сейчас для конфиденциальности эти поля пустые.

**Comment by MrZillaGold** [comment]
Это происходит из-за содержания в коротком адресе группы спец. символов, доступный диапазон символов `a-zA-Z_\-0-9`.
В качестве временного решения можно использовать нормальный id группы в формате: `public175914098`. Позже выпущу фикс для самого скрипта.

**Comment by d3adwolf** [comment]
> Это происходит из-за содержания в коротком адресе группы спец. символов, доступный диапазон символов `a-zA-Z_\-0-9`, скорее всего в вашем адресе есть точка, которую использовать для метода хранилища VK нельзя.
> В качестве временного решения можно использовать нормальный id группы в формате: `public175914098`. Позже выпущу фикс для самого скрипта.

Лично мне помогло, спасибо, я думаю надо в `README` это упомянуть.

**Comment by MrZillaGold** [comment]
Можно уже отдельно не выносить, выпущена версия 3.0.2 в которой это исправлено.

**Comment by d3adwolf** [comment]
> Можно уже отдельно не выносить, выпущена версия [3.0.2 ](https://github.com/MrZillaGold/VK2Discord/releases/tag/3.0.2)в которой это исправлено.

Так у меня 3.0.2 и ошибка есть. 

- Ubuntu 22.04 LTS

**Comment by MrZillaGold** [comment]
Какой id группы?

**Comment by MrZillaGold** [comment]
В [3.0.3](https://github.com/MrZillaGold/VK2Discord/releases/tag/3.0.3) должно исправиться

**Comment by d3adwolf** [comment]
> Какой короткий адрес группы?

astis.unturned / astis.minecraft / astis.rust.legacy

**Comment by d3adwolf** [comment]
> В [3.0.3](https://github.com/MrZillaGold/VK2Discord/releases/tag/3.0.3) должно исправиться

Щас гляну..
