### ISSUE TITLE
Не публикуются записи в Discord

### ISSUE THREAD

**Issue by A001AA01** [MrZillaGold/VK2Discord#485]
**Описание ошибки**
Когда отправляю пост в Вк, в Дискорде он не появляется.

**Шаги воспроизведения**
1. Делаю по инструкции
2. Проверяю все версии в консоли
3. Докачиваю необходимые данные при помощи **npm i**
4. Запускаю скрипт **npm start** 
5. В консоли вижу, что подключение есть и все окей
6. Отправляю пост в ВК - в Дискорде он не приходит.

**Скриншоты**

![2022-04-18_14-33-58](https://user-images.githubusercontent.com/99471552/163774028-9dfef433-dd37-4b27-a2a5-559f2a74ae37.png)
![2022-04-18_14-46-13](https://user-images.githubusercontent.com/99471552/163774816-2062c0f9-d376-41e4-ab39-72846be76594.png)
![2022-04-18_14-46-48](https://user-images.githubusercontent.com/99471552/163774887-6bb969bd-605a-4bd5-a428-8d43906a7cf4.png)
![2022-04-18_14-48-22](https://user-images.githubusercontent.com/99471552/163775136-49cc201a-bdd2-4ccc-9a68-503b5b5b4fe2.png)

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| NodeJS     | `17.9.0`    |
| npm        | `8.5.5`    |
| VK2Discord | `3.0.1`    |

**Comment by MrZillaGold** [comment]
![image](https://user-images.githubusercontent.com/42776347/163800812-a3fc37e4-a695-489e-8e76-446344f6221c.png)

Вы в конфиге исключаете из публикации видео, текст и изображения, по факту получается пустая запись, которая не публикуется скриптом. 

[**Описание полей конфига**](https://github.com/MrZillaGold/VK2Discord/blob/master/CONFIG_FIELDS.md)
