### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by A001AA01** [MrZillaGold/VK2Discord#490]
**Описание ошибки**
При отправке поста в Группу "ВК", в консоле выдает ошибку, но я не знаю в чем проблема, файл в котором описана сама ошибка, я могу отправить через телеграмм.  Извиняюсь, что снова отвлекаю от дел ))

**Шаги воспроизведения**
1. Запустить скрипт 
2. Отправить Пост
3. Не понимать в чем ошибка. 

**Скриншоты**
![2022-04-19_23-14-20](https://user-images.githubusercontent.com/99471552/164048677-7583f42e-fad9-403d-ae46-a2791cd8973a.png)

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| NodeJS     | `17.9.0`    |
| npm        | `8.5.5`    |
| VK2Discord | `3.0.1`    |

**Comment by MrZillaGold** [comment]
Следим за решением здесь: https://github.com/MrZillaGold/VK2Discord/issues/483
