### ISSUE TITLE
[Bug] Неправильное отображение русских символов во вложении ссылки на статью

### ISSUE THREAD

**Issue by Foxie117** [MrZillaGold/VK2Discord#492]
**Описание ошибки**
Вместо русских букв кракозябры

**Шаги воспроизведения**
Сделать пост со статьёй и названием на русском языке

**Скриншоты**
![image](https://user-images.githubusercontent.com/48993952/164989761-cc7746d7-ff0b-4580-809c-e80981c113e9.png)
![image](https://user-images.githubusercontent.com/48993952/164989767-061ae06d-c710-4adf-9504-86c2a2efa28a.png)

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| NodeJS     | `17.9.0`    |
| npm        | `8.5.5`    |
| VK2Discord | `Взята последняя мастер версия`    |

**Comment by MrZillaGold** [comment]
Проблема вк: https://github.com/MrZillaGold/VK2Discord/issues/21
