### ISSUE TITLE
Перестал работать скрипт

### ISSUE THREAD

**Issue by fr1nd4** [MrZillaGold/VK2Discord#53]
После обновления перестал работать скрипт
Пробовал переустановить и обновить node js, не помогло
Как бы не настраивал config вылетает одна и та же ошибка

![image](https://user-images.githubusercontent.com/64887288/90685635-4cd0a200-e294-11ea-9536-3f56857e774d.png)
![image](https://user-images.githubusercontent.com/64887288/90685875-a0db8680-e294-11ea-93d4-4dd428e4e43b.png)

**Comment by MrZillaGold** [comment]
Установите зависимости: `npm i`

**Comment by fr1nd4** [comment]
Спасибо
Ставлю класс
