### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by dedmazahai** [MrZillaGold/VK2Discord#56]
Привет, столкнулся с такой ошибкой. После публикации поста в паблике
![image](https://user-images.githubusercontent.com/37226719/91612416-0e1ea400-e986-11ea-90cd-b8c759cf120d.png)

**Comment by MrZillaGold** [comment]
Можно скриншот конфига? При этом нужно замазать токен и вебхуки.

**Comment by dedmazahai** [comment]
Вот пожалуйста)
![image](https://user-images.githubusercontent.com/37226719/91631268-0f30ef00-e9e1-11ea-9565-f62097dd5e6e.png)

**Comment by dedmazahai** [comment]
Поменял токен и вот, тоже самое
![image](https://user-images.githubusercontent.com/37226719/91631373-ba41a880-e9e1-11ea-8d6f-43c82844349e.png)

**Comment by dedmazahai** [comment]
Спасибо за помощь, Разобрался
