### ISSUE TITLE
[Feature request] Есть ли официальный docker-образ приложения?

### ISSUE THREAD

**Issue by stamepicmorg** [MrZillaGold/VK2Discord#62]
**Описание возможности**
Есть ли официальный docker-образ приложения? Моя экосистема построена на контейнерах. На хабе не нашел (видимо нету). Поддержка докера была бы офигенной.

ps свой приватный для себя создать не проблема.

**Comment by MrZillaGold** [comment]
В данный момент нет, как появится под рукой компьютер, почитаю про Docker.

**Comment by stamepicmorg** [comment]
могу поиграться и выслать пример в PR

**Comment by MrZillaGold** [comment]
Конфиг для Docker добавил, сам образ в Hub загружу позже

**Comment by GermanRuss** [comment]
Ну как там с Docker?

**Comment by MrZillaGold** [comment]
Немного терпения, в субботу постараюсь залить

**Comment by MrZillaGold** [comment]
[Залил в Docker](https://hub.docker.com/repository/docker/mrzillagold/vk2discord), жду фидбек по работе, чтобы закрыть issue.

**Comment by stamepicmorg** [comment]
о, огонь, протещу вечерком, отпишусь.

**Comment by MrZillaGold** [comment]
`latest` добавлю.

По поводу env думаю это излишне, раньше скрипт поддерживал переменные окружения, но из-за поддержки, как я их называю, кластеров пришлось отказаться. По итогу получается очень сложная настройка для конечного пользователя. JSON конфиг самый оптимальный вариант, но хотя не совсем безопасный.

Если вопрос на этом закрыт, можете закрывать issue.

**Comment by stamepicmorg** [comment]
Да, думаю, ок, спасибо!

Про переменные env я имел ввиду для докера. Чтобы не сам файл отконфигуреный прокидывать внутрь, а что-бы при запуске контейнера в этот самый json добавлялись значения из docker compose\run параметров. у меня так с jira сделано.

потом могу пример скинуть. но, думаю, для обычных пользователей это будет overhead.
