### ISSUE TITLE
Не отправляются посты

### ISSUE THREAD

**Issue by oleg054** [MrZillaGold/VK2Discord#647]
**Описание ошибки**

Запустил скрипт вроде без ошибок но при этом он не отправляет посты с вк в дс. 
![image](https://user-images.githubusercontent.com/103387254/195976404-47002679-48b4-4f2d-8807-0a92b9627fc3.png)

**Версии**
windows10
| ---------- | ------ |
| NodeJS     | `v18.11.0`    |
| npm        | `v18.11.0`    |
| VK2Discord | `3.0.3`    |

**Comment by MrZillaGold** [comment]
События в настройках Longpoll API на новые записи активированы? Также проверь что версия API стоит сама последняя - 5.131 и выше.

**Comment by oleg054** [comment]
> События в настройках Longpoll API на новые записи активированы? Также проверь что версия API стоит сама последняя - 5.131 и выше.

А не подскажете как исправить 
![image](https://user-images.githubusercontent.com/103387254/196007212-88ccb109-34d3-4b8e-a4cb-faf47576a4ff.png)

**Comment by MrZillaGold** [comment]
Нужно в ссылках на вебхук discord app поменять на discord
