### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by FortunaX** [MrZillaGold/VK2Discord#712]
![2023-01-04_18-57-17](https://user-images.githubusercontent.com/121942387/210570735-a0e2e18f-ea2e-41c7-83c0-25172d563596.png)
![2023-01-04_18-56-04](https://user-images.githubusercontent.com/121942387/210570747-8a8f4be6-7266-48a7-9579-b12708653084.png)
**Описание ошибки**
Чёткое и понятное описание.
at ParallelWorker.execute (file:///C:/VK2Discord-master/node_modules/vk-io/lib/index.mjs:1663:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(node:2936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 50)

**Шаги воспроизведения**
1. Зайдите '...'
2. Нажмите '....'
3. Спуститесь '....'
4. Получите ошибку

**Скриншоты**
По возможности прикрепите скриншот с ошибкой, это поможет в поиске причины проблемы.

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| NodeJS     | 19.3.0   |
| npm        | 9.2.0   |
| VK2Discord | 3.0.4    |

**Comment by MrZillaGold** [comment]
Перегенерируй токен по инструкции, проверь что копируешь его правильно - в инструкции это описано
