### ISSUE TITLE
Некорректное отображение поста

### ISSUE THREAD

**Issue by PandorumGo** [MrZillaGold/VK2Discord#72]
**Описание ошибки**
При публикации поста в группе VK (предложенный пост(не от имени Группы) ) с несколькими "картинками"(в одном посте), в DC передается только одна (первая) "картинка". (Извините за мат в скриншотах) 

**Шаги воспроизведения**
1. Публикация поста в VK
2. Появление поста в DC
3. Получите ошибку

**Версии**
| NodeJS     | `12.19.0`    |
| npm        | `6.14.8`    |
| VK2Discord | `1.9.3`    |
![Screenshot_2020-10-20-12-21-30-448_com discord-01](https://user-images.githubusercontent.com/69967280/96570802-77aa9700-12d3-11eb-878c-45932dbdace7.jpeg)
![Screenshot_2020-10-20-12-21-53-699_com vkontakte android-01](https://user-images.githubusercontent.com/69967280/96570807-79745a80-12d3-11eb-9b7a-48059ebe592f.jpeg)

**Comment by PandorumGo** [comment]
Используется LongPoll API

**Comment by PandorumGo** [comment]
Так же при просмотре изображения через DC, в названии почему то пишет ссылка на Twitter
![Screenshot_2020-10-20-13-05-06-466_com discord-01](https://user-images.githubusercontent.com/69967280/96571967-f7853100-12d4-11eb-854c-4f7e7c2a1c60.jpeg)

**Comment by MrZillaGold** [comment]
Это механика Discord, на телефонах будет отображаться только 1 картинка из поста, в приложении на компьютере от 4-10 (зависит от из размера).
Ссылка Twitter нужна для правильной работы, проблем это вызывать не должно.

Если вопросов больше нет - можете закрыть issue.

**Comment by PandorumGo** [comment]
Понял, спасибо за ответ.
