### ISSUE TITLE
no index.js file to run it[Bug]

### ISSUE THREAD

**Issue by AlexLovser** [MrZillaGold/VK2Discord#729]
**Описание ошибки**
I ve installed all following the instruction. But when i do "node index.js" or "npm start" etc. I receive en error,
`Cannot find module '/home/VK2Discord/dist/index.js'`
How to fix it?

**Comment by MrZillaGold** [comment]
Run `npm run-script build` or download the build from [releases](https://github.com/MrZillaGold/VK2Discord/releases)
