### ISSUE TITLE
[Bug] Ошибка при отправке сообщения

### ISSUE THREAD

**Issue by asupreme1337** [MrZillaGold/VK2Discord#737]
**Описание ошибки**
С недавнего времени перестали отправляться сообщения из ВК в Дискорд. Обновился на последнюю версию скрипта, обновил nodejs, но проблему это не исправило.

**Шаги воспроизведения**
1. Создать пост в группе ВКонтакте
2. Смотреть консоль на сервере
3. Получим ошибку

**Скриншоты**
Приложу пасту с ошибкой: https://pastebin.com/VBms4Fxk
Паста с успешным подключением кластеров: https://pastebin.com/7zpf9cWU

**Версии**
| Платформа  | Версия | 
| Ubuntu | 20.04.5 LTS |
| NodeJS     | `19.6.0`    |
| npm        | `9.5.0`    |
| VK2Discord | `3.0.4`    |

**Comment by MrZillaGold** [comment]
Необзодимо заполнить поле username в конфиге, discord ввел ограничение на пустое содержимое этого поля
