### ISSUE TITLE
[Bug] Не полностью передаётся хештег из поста

### ISSUE THREAD

**Issue by Mihanoks** [MrZillaGold/VK2Discord#749]
**Описание ошибки**
В конце каждого поста в группе есть тематических хештег (например, #новости@earthm1ne). Этот хештег передаётся в дискорд неполностью, только часть "#новости@earthm".

**Шаги воспроизведения**
1. Создайте пост в ВК с хештегом в конце
2. Проверьте пост в дискорде

**Скриншоты**
![image](https://user-images.githubusercontent.com/91060150/227727053-0512fd0d-7aa2-4f09-b4c9-92cbbea19adf.png)
![image](https://user-images.githubusercontent.com/91060150/227727060-7b7e549e-c95e-4f5e-aa32-9e02ef5574c3.png)

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| NodeJS     | `19.8.1`    |
| npm        | `9.5.1`    |
| VK2Discord | `3.0.4`    |

**Comment by Mihanoks** [comment]
Когда исправите? Мне пришлось отказаться от вашего скрипта, ибо он перестал нормально работать и не была исправлена эта ошибка.

**Comment by egorprnn** [comment]
Исправил

https://github.com/MrZillaGold/VK2Discord/commit/9548188a927c83b826f82279f598c6e489778cf8

https://github.com/MrZillaGold/VK2Discord/releases/tag/3.0.5

По другим проблемам нужно открывать другие issue с описанием проблемы.
