### ISSUE TITLE
[Bug] ExecuteError: Code №100 - One of the parameters specified was missing or invalid

### ISSUE THREAD

**Issue by EscapedM** [MrZillaGold/VK2Discord#754]
Несколько дней назад прошлый релиз 3.0.4 стал выдавать ошибку, что в заголовке темы.
Попробовал обновить - без изменений.
Переустановил с нуля, попробовал на другом устройстве уже с версией 3.0.5 - то же самое.
После замены  --unhandled-rejections=warn на  --unhandled-rejections=strict стал выдавать в консоль подробности об ошибке.

 
![изображение](https://github.com/MrZillaGold/VK2Discord/assets/94228994/f042b417-8eac-4ab1-9032-2edbd0b90ee9)

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| NodeJS     | `19.9,0`    |
| npm        | `9.7.1`    |
| VK2Discord | `3.0.5`    |

Установленные пакеты:
![изображение](https://github.com/MrZillaGold/VK2Discord/assets/94228994/6ef0e070-593e-4cd8-b2f3-4341502e8305)

Система: Raspbian GNU/Linux 11 (bullseye) armhf

**Comment by egorprnn** [comment]
Перегенерируйте токены от страниц используя [ссылку](https://oauth.vk.com/authorize?client_id=2685278&scope=1073737727&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token&revoke=1)

**Comment by EscapedM** [comment]
Да, так действительно помогло.
