### ISSUE TITLE
[Feature request] Повторная отправка последнего поста

### ISSUE THREAD

**Issue by TETSUKER** [MrZillaGold/VK2Discord#765]
**Описание ошибки**
Не отправляется повторно самый верхний пост группы при запуске через docker compose.

**Шаги воспроизведения**
1. Создать docker-compose.yml и config.json;
2. Запустить docker compose up -d;
3. Проверить, что самый верхний пост отправился;
4. Хотим поменять токены или цвета и проверить, что посты снова будут отправляются;
5. Перезапускаем compose;
6. Видим в логах контейнера: "[!] Новых записей в кластере 1 нет.";
7. Ожидание, что при перезапуске снова отправится последний пост для проверки изменения конфигурации либо дать знать как очистить историю отправленных постов.

**Comment by egorprnn** [comment]
Такой возможности действительно нет, для тестировани изменений рекомендую использовать тестовую группу, в которой публиковать новый пост сразу после правок конфига, позже менять значения группы на исходные, цвета можно проверять отправкой сообщения по ссылке хука через сайт

https://toolscord.com/webhook
