### ISSUE TITLE
[Bug] просит какой-то index.js

### ISSUE THREAD

**Issue by Oktivle** [MrZillaGold/VK2Discord#767]
**Описание ошибки**
При попытке запустить скрипт прилетает ошибка 'Error: Cannot find module 'C:\Users\Vitja\Downloads\VK2Discord-3.0.5\dist\index.js'

**Шаги воспроизведения**
1. Следовать инструкции по установке.
2. Ввести команду 'npm start'
3.Получите ошибку.

**Скриншоты**
![изображение_2024-06-28_213920481](https://github.com/MrZillaGold/VK2Discord/assets/97593220/a8d60e89-4029-40f5-9fb8-c2e148fba24b)

**Версии**
| Windows  | 11 | 
| NodeJS     | `20.15.0`    |
| npm        | `10.8.1`    |
| VK2Discord | `3.0.5`    |

**Comment by egorprnn** [comment]
Следуйте [инструкции по настройке](https://github.com/MrZillaGold/VK2Discord/wiki/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F), ошибки не будет если сделать все по описанным шагам
