### ISSUE TITLE
[Bug] Вложение статья.

### ISSUE THREAD

**Issue by Dancbeunny98** [MrZillaGold/VK2Discord#80]
![image](https://user-images.githubusercontent.com/37336183/98284523-4a880500-1fb2-11eb-9210-7ca45c49057b.png)

Если тыкнуть на 

![image](https://user-images.githubusercontent.com/37336183/98284537-51167c80-1fb2-11eb-8a43-4c1c5c40ff9b.png)

То переводит на мобильную версию.

![image](https://user-images.githubusercontent.com/37336183/98284466-380dcb80-1fb2-11eb-8a7f-de85ccfa1fba.png)

**Comment by Dancbeunny98** [comment]
Версия vk2discord последняя.

**Comment by MrZillaGold** [comment]
Проблема ВКонтакте.
Прошу оформлять issue по шаблону который дается в начале.
