### ISSUE TITLE
Запуск скрипта из под pm2

### ISSUE THREAD

**Issue by SniffRx** [MrZillaGold/VK2Discord#81]
Пытаюсь запустить скрипт из под pm2, но не работает. (под npm запускает отлично) PS. Запускал под ssh>root
Но в моей панели нельзя запускать npm, только pm2

**Версии**
| Платформа  | Версия | 
| ---------- | ------ |
| NodeJS     | `14.15.0`    |
| npm        | `6.14.8`    |
| PM2 | `4.5.0`    |
| VK2Discord | `1.9.4`    |

![image](https://user-images.githubusercontent.com/37187657/98563359-241cdf00-22bc-11eb-8d0c-e805ab87afb9.png)

**Comment by MrZillaGold** [comment]
Так как скрипт использует экспериментальные функции NodeJS вам необходимо использовать [файл экосистемы](https://pm2.keymetrics.io/docs/usage/application-declaration/#ecosystem-file).

Скрипт запускается при помощи команды:
`node --experimental-modules --experimental-json-modules index.mjs`

`--experimental-modules` `--experimental-json-modules` являются параметрами для запуска NodeJS, их необходимо передать полем [`node-args`](https://pm2.keymetrics.io/docs/usage/application-declaration/#general) в файле экосистемы pm2.

Если вопросов больше нет, можете закрывать issue.
