### ISSUE TITLE
Ошибка при выполнении запроса

### ISSUE THREAD

**Issue by metamopqoz** [MrZillaGold/VK2Discord#82]
Все стоит на последний версии.Все делал по инструкции,но ничего не сработало,выдает только такое сообщение (см. скрин №1).
![343434](https://user-images.githubusercontent.com/61648857/99882744-dc8b4100-2c33-11eb-8614-c94b6c9cb8d8.png)

**Comment by MrZillaGold** [comment]
Могу предположить что вы пытаетесь запустить скрипт из Украины. Тогда нужно использовать VPN.

**Comment by LWJerri** [comment]
Ошибка со стороны Discord'a. 

```js
A request took longer than the specified restRequestTimeout (15 seconds by default), and was aborted to not lock up the request handler. It can be an internal server error on Discord's side, or just a slow connection. In case of the latter, the restRequestTimeout option in ClientOptions (https://discord.js.org/#/docs/main/stable/typedef/ClientOptions) can be increased to prevent future AbortErrors.
```

**Comment by LWJerri** [comment]
> Могу предположить что вы пытаетесь запустить скрипт из Украины. Тогда нужно использовать VPN.

Запускаю с Украины без VPN и всё работает отлично.

**Comment by MrZillaGold** [comment]
@LWJerri по стеку ошибки это не проблема Discord, то что ваш провайдер не блокирует подключение к ВК не означает, что его не могут блокировать другие провайдеры. (По опыту других пользователей скрипта)

**Comment by LWJerri** [comment]
> @LWJerri по стеку ошибки это не проблема Discord, то что ваш провайдер не блокирует подключение к ВК не означает, что его не могут блокировать другие провайдеры. (По опыту других пользователей скрипта)

Мой провайдер блокирует ВК, но ВК нашла способ это обойти, поэтому даже не знаю что Вам сказать..

**Comment by metamopqoz** [comment]
Новая ошибка.Я,кстати,включил ВПН.
![Screenshot_3](https://user-images.githubusercontent.com/61648857/99914187-5a1e8200-2d04-11eb-8521-c13096716572.png)

**Comment by LWJerri** [comment]
> Новая ошибка.Я,кстати,включил ВПН.
> ![Screenshot_3](https://user-images.githubusercontent.com/61648857/99914187-5a1e8200-2d04-11eb-8521-c13096716572.png)

Тебе же ясно написано причину ошибки.

**Comment by metamopqoz** [comment]
ТАК А КАКОЙ USER?

**Comment by metamopqoz** [comment]
Все,причину выяснил.Надо было перед айди группы поставить ( - )  и всё.Скрипт отлично пашет.Спасибо!
