### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Darksimus1** [MrZillaGold/VK2Discord#83]
Удостоверился, что токен и айди группы были правильны, но всё равно не работает.
![изображение](https://user-images.githubusercontent.com/50050567/99884167-e1f58500-2c4d-11eb-98c1-7d49d9bd3e93.png)

**Comment by MrZillaGold** [comment]
longpoll: true стоит?

**Comment by Darksimus1** [comment]
Да, стоит

**Comment by MrZillaGold** [comment]
У токена есть право доступа на управление сообществом?
![image](https://user-images.githubusercontent.com/42776347/99900290-6271bf80-2cfa-11eb-9842-4b95f200fec0.png)

**Comment by MrZillaGold** [comment]
Также по поводу longpoll: true, по логам из консоли оно у вас в конфиге 100% не стоит.

**Comment by Darksimus1** [comment]
А, и вправду забыл про true. Я думал, я его поставил.
Спасибо.
