### ISSUE TITLE
Не работают упоминания ролей 

### ISSUE THREAD

**Issue by sirok1** [MrZillaGold/VK2Discord#88]
Бот как бы просто пишет текстом @роль. Также я пробовал и <@роль> и <@&роль>. Есть какое-нибудь решение ?

**Comment by MrZillaGold** [comment]
Попробуйте такой синтаксис: `<@& ID-Роли>`
Например: `<@&467588814580350986>`

ID-Роли можно получить с [включенным режимом разработчика Discord](https://support.discord.com/hc/ru/articles/206346498-%D0%93%D0%B4%D0%B5-%D0%BC%D0%BD%D0%B5-%D0%BD%D0%B0%D0%B9%D1%82%D0%B8-ID-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B0-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F-), зайдите в меню ролей сервера - ПКМ по нужной роли - Копировать ID

**Comment by sirok1** [comment]
Спасибо, заработало )

**Comment by sirok1** [comment]
Спасибо, починилось )
