### ISSUE TITLE
Как добавить в кфг несколько сообществ?

### ISSUE THREAD

**Issue by sirok1** [MrZillaGold/VK2Discord#89]
в описании кфг, написано, что можно указать несколько сообществ, но и при указании через запятую и при указании без запятых , сервис крашится. вот пример 

>"group_id": "example1","example2",

**Comment by MrZillaGold** [comment]
Ничего подобного там не сказано, посмотреть, как можно добавлять несколько сообществ можно в примере конфига: https://github.com/MrZillaGold/VK2Discord/blob/master/config_example.json

**Comment by sirok1** [comment]
![Uploading image.png…]()

**Comment by sirok1** [comment]
![image](https://user-images.githubusercontent.com/75698544/101643684-6e24ec00-3a45-11eb-8c82-10eecffd4b23.png)

**Comment by MrZillaGold** [comment]
Это пример заполнения, они не перечисляются через запятую, а просто показывается что можно использовать и короткие адреса сообществ и обычные с id

**Comment by sirok1** [comment]
Хорошо, спасибо
