### ISSUE TITLE
При использовании контейнера linux.[Bug]

### ISSUE THREAD

**Issue by GermanRuss** [MrZillaGold/VK2Discord#93]
Ошибка при посте в вк
Пост не отправляется.
Консоль dockera:
`TypeError: Cannot read property 'is_donut' of undefined
    at Sender.handle (file:///usr/src/vk2discord/modules/Sender.mjs:43:42)
    at file:///usr/src/vk2discord/modules/Handler.mjs:103:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /usr/src/vk2discord/node_modules/middleware-io/lib/index.js:280:9
`
Ошибка
[https://s8.hostingkartinok.com/uploads/images/2020/12/0e74ad9f14b100587aefb65525fea2a6.png](url)
конфиг
[https://s8.hostingkartinok.com/uploads/images/2020/12/51d3a1c5d5463844ea4b731881ec0886.jpg](url)

Версия 2.0.0

**Comment by MrZillaGold** [comment]
Версию LongPoll API повысьте до последней

**Comment by GermanRuss** [comment]
Большое спасибо!
