### ISSUE TITLE
[Bug] Cannot read property 'lenght' of underfind

### ISSUE THREAD

**Issue by SkinH** [MrZillaGold/VK2Discord#95]
**Описание ошибки**
Запустился скрипт без каких-либо ошибок, но как только запись постится в ВК вылезает данная ошибка и в ДС ничего не постится

Файл config.json ---> 
![изображение](https://user-images.githubusercontent.com/62944380/102468520-abe7cd00-4062-11eb-9a31-739e43dfdfbd.png)
![изображение](https://user-images.githubusercontent.com/62944380/102468758-ff5a1b00-4062-11eb-835d-e86abdc74684.png)

Скрин ---> 
![изображение](https://user-images.githubusercontent.com/62944380/102467093-eea8a580-4060-11eb-98e2-a56f34226f3e.png)

**Шаги воспроизведения**
1. Склонил с GitHub версию 2.0.0 `git clone -b 2.0.0 https://github.com/MrZillaGold/VK2Discord.git`
2. Перешел в папку VK2Discord
3. Прописал `npm i`
4. Заполнил config.json
5. Запустил командой `npm start`
6. При постинге в группе ВК вылезла ошибка

**Версии**
| Ubuntu  | 16.04 | 
| ---------- | ------ |
| NodeJS     | `15.4.0`    |
| npm        | `7.0.15`    |
| VK2Discord | `2.0.0`    |

**Comment by MrZillaGold** [comment]
Куда поле 'words_blacklist' из конфига дели? Удалите конфиг и запустите скрипт - сгенерируется новый конфиг настройте его заново.

**Comment by MrZillaGold** [comment]
Надеюсь мой ответ помог вам, если что пингуйте.

**Comment by SkinH** [comment]
Добрый день! Перезаполнил новый сгенерированный конфиг и все заработало.
