### ISSUE TITLE
[Bug] Дублирование постов (HEROKU)

### ISSUE THREAD

**Issue by LordCherry** [MrZillaGold/VK2Discord#96]
Привет! 
Столкнулся с проблемой, когда при добавлении нескольких сообществ бот начинает дублировать сообщения (у меня подключено 2 группы: одна работает с longpoll, вторая через токен личной страницы. 
Так вот, почитав весь Issue не нашел решения проблемы, потому пришлось немного повозиться и решать проблему самостоятельно.

Собстна, бот находится у меня на **Heroku**. Дублирование постов происходило из-за одновременной активации "_web npm start_" и _"worker npm start_". Для исправления возникающего бага достаточно отключить одну из настроек (скриншот ниже):

![image](https://user-images.githubusercontent.com/12301411/103059576-8bfe5f00-45b6-11eb-82a9-dce654212b37.png)

_Доп инфа, которая может быть важной._ 

Для каждой из групп я использую два разных вебхука (дискорд), все новости постятся в один канал.

**Comment by MrZillaGold** [comment]
Логично что нужно отключить одну из опций - скрипт не веб приложение, это не баг скрипта.
